In [1]:
print("hello world")

hello world


In [2]:
#Start NumPy
import numpy as np

In [3]:
data = [1,2,,3,4,5 ] # data List
data

SyntaxError: invalid syntax (<ipython-input-3-7ee7d801b359>, line 1)

In [4]:
data = [1,2,3,4,5 ] # data List
data

[1, 2, 3, 4, 5]

In [5]:
np.array (data) #mengubah list menjadi array

array([1, 2, 3, 4, 5])

In [6]:
np.arange(0,10) #membuat data array numpy  secara otomatis

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10,2) #2 merupakan kelipatan 

array([0, 2, 4, 6, 8])

In [8]:
np.linspace(0,10,3) #membuat array dummy

array([ 0.,  5., 10.])

In [9]:
np.linspace (0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [10]:
np.random.rand(3) #membuat aray dummy random

array([0.18114564, 0.17233619, 0.87666058])

In [11]:
np.random.rand(3,3) 

array([[0.68388498, 0.0687755 , 0.03616162],
       [0.85383841, 0.73561943, 0.39386527],
       [0.3338763 , 0.2344187 , 0.74435455]])

In [12]:
np.random.rand(5,7)

array([[0.12279169, 0.17836846, 0.96862534, 0.04035552, 0.14493432,
        0.88757439, 0.7498376 ],
       [0.66373799, 0.4610212 , 0.96754652, 0.21685494, 0.73315299,
        0.7960096 , 0.45328305],
       [0.00816027, 0.89866809, 0.27646429, 0.01783527, 0.33321846,
        0.63725923, 0.14053658],
       [0.90723515, 0.66566512, 0.96307235, 0.54240507, 0.51047907,
        0.48803297, 0.55977473],
       [0.41396543, 0.64106031, 0.2868789 , 0.21517767, 0.21731273,
        0.72474344, 0.87086045]])

In [13]:
np.random.randn(5,5) #membuat array random negative dan positive

array([[-1.58107306,  0.64872283, -0.35387332,  0.09402121, -0.54917841],
       [ 1.56069497, -0.48388534, -0.81096831, -0.29983285, -0.00277246],
       [ 0.0303066 , -1.02706209,  0.60510623,  0.60679306,  0.30174615],
       [ 1.16477885,  0.027158  , -0.26051084, -0.38106895,  0.6486634 ],
       [-0.64113369, -0.62557876,  1.00615759, -0.90307933, -1.08544066]])

In [14]:
np.random.randint(1,50) #membuat data array random bilangan bulat

23

In [15]:
np.random.randint(1,50,10)

array([13, 15, 40, 13, 15, 17, 33, 29, 35, 16])

In [16]:
arr = np.arange(25)

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [18]:
arr.reshape (5,5) #mengubay array 1 dimensi menjadi 2 dimensi

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
arr.max() #nilai array terbsar

24

In [21]:
arr.min() #nilai array terkecil

0

In [22]:
arr.argmax() #index nilai terbesar 

24

In [23]:
arr.argmin() #index nilai terkecil

0

In [24]:
arr.sum() #menjumlahkan nilai array

300