In [1]:
import numpy as np

In [3]:
arr = np.arange(10)
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr[7] #mendapatkan nilai sebuah index array

7

In [6]:
arr[0:3] #mendapat nilai dari jarak index

array([0, 1, 2])

In [7]:
arr[0] = 9 #mengubah data array numpy

In [8]:
arr

array([9, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr [0:5] = 9 # merubahd data dari jarak index

In [10]:
arr

array([9, 9, 9, 9, 9, 5, 6, 7, 8, 9])

In [12]:
data = arr[0:5]

In [13]:
data

array([9, 9, 9, 9, 9])

In [14]:
data [:] = 99 # merubah semua data array :menunjuk semua
data

array([99, 99, 99, 99, 99])

In [21]:
newData = arr.copy() # menduplikasi suatu data pada numpy agar bisa di rubah datanya

In [22]:
newData

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

In [23]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [24]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[2] # menampilkan array 2d index ke 2 atau baris ke 2

array([35, 40, 45])

In [26]:
arr_2d[2][1]#menampilkan array 2d index ke2 kolom ke 1

40

In [27]:
arr_2d[1][2] # menampilkan array 2d index ke2 kolom ke 2

30

In [28]:
arr_2d[2,1] #menampilkan array 2d index ke2 kolom ke 1

40

In [29]:
arr_2d[0:2,1:3]
#menampilkan array berdasarkan rangenya dimana:
# 0:2 adalah menampilkan index 0 sampai dengan index dibawah 2
# 1:3 adalah menampilkan kolom 1 sampai dengan kolom di bawah 3

array([[10, 15],
       [25, 30]])

In [30]:
arr_2d[:2,1:]
 # :2 dapat did artikan menampilkan index yang di bawah dari index 2 berarti index 0 dan index 1
# :1 dapat di artikan menampilkan kolom 1 atau yang diatas dari kolom 1 berarti kolom 2

array([[10, 15],
       [25, 30]])

In [31]:
nilai = np.arange (1,11)

In [32]:
nilai

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
nilai > 5 # menseleksi data array

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [35]:
nilai [nilai > 5] #menseleksi data array

array([ 6,  7,  8,  9, 10])

In [36]:
nilai + nilai 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [38]:
nilai * nilai 

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [42]:
nilai - nilai 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [44]:
nilai / nilai 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])